config/routes.rb
Geo::Application.routes.draw do
  resources :visits

  root :to => 'visits#new'
  

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :city, :country, :ipaddress
  
=begin
  geocoded_by :ipaddress,
  
     :city => :city, :country => :country
  
  after_validation :geocode
=end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    #@ip = request.remote_ip
    #@city = request.location.city
    #@country = request.location.country
    @visit = Visit.new
    @visit.ipaddress = request.remote_ip
    @visit.city = request.location.city
    @visit.country = request.location.country
    
    if @visit.save
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
    
    else
    root_path
    end
    
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<h2>Geo app </h2>
</header>
<%= yield %>

</body>
</html>

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ipaddress %><br />
    <%= f.text_field :ipaddress %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
  <tr>
    <th>Ipaddress</th>
    <th>City</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
	<td><%= visit.id %></td>
    <td><%= visit.ipaddress %></td>
    <td><%= visit.city %></td>
    <td><%= visit.country %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

Hola!


your IP ADDRESS is: <%= request.remote_ip %> <br />

your CITY is :<%= request.location.city %> <br />

YOUR COUNTRY is: <%= request.location.country %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ipaddress:</b>
  <%= @visit.ipaddress %>
</p>

<p>
  <b>City:</b>
  <%= @visit.city %>
</p>

<p>
  <b>Country:</b>
  <%= @visit.country %>
</p>


<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>